// Exam code → Department display name mapping for print sheets.
export const EXAM_CODE_DEPT_MAP: Record<string, string> = {
  CPZ6B: 'B.COM',
  CYA6E: 'B.COM(CS)',
  CPG6A: 'B.COM',
  MAT6A: 'BCOM[ISM]',
  MAM4P: 'BBA',
  CPC6C: 'B.COM',
  TAG6B: 'B.SC',
  CPM6A: 'B.COM',
  AXA6B: 'B.A',
  ANA6B: 'B.A',
  AQA6B: 'B.A',
  MFF2C: 'M.SC',
  SAT6B: 'B.SC',
  SAY6B: 'B.SC',
  TAK6B: 'B.SC',
  MCQAC: 'M.SC',
  SAZ5B: 'B.C.A',
  SAU5B: 'B.SC',
  MAM3J: 'BBA',
  HAU2B: 'M.A',
  'MAM3J(ISM)': 'BCOM[ISM]',
  CYA5B: 'B.COM(CS)',
  BPZ6B: 'B.COM',
  'MAM4P(ISM)': 'BCOM[ISM]',
  SAX5A: 'BSC[VC]',
  BPC6C: 'B.COM',
  BPG6A: 'B.COM',
  BPZ5B: 'B.COM',
  BYA5B: 'B.COM(CS)',
  CPZ5B: 'B.COM',
  SAD5B: 'B.SC',
  TAK5B: 'B.SC',
  ANA5B: 'B.A',
  BPC5C: 'B.COM',
  BYA6B: 'B.COM(CS)',
  CPG5A: 'B.COM',
  CPM5A: 'B.COM',
  CYA6B: 'B.COM(CS)',
  TAG5B: 'B.SC',
  CPC5B: 'B.COM',
  CPW5A: 'B.COM',
  CPW6C: 'B.COM',
  'MAM3J(BSC)': 'BSC[ISM]',
  MCG3A: 'M.SC',
  MCR2C: 'M.SC',
  PSDEJ: 'M.SC(CS)',
  SAK5B: 'B.SC',
  'SAX5A(VC)': 'BSC[VC]',
  SAY5B: 'B.SC',
};

export function deptFromExamCode(code: string): string {
  return EXAM_CODE_DEPT_MAP[code] || EXAM_CODE_DEPT_MAP[code.toUpperCase()] || '';
}
